CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS wallet (
    user_id INT PRIMARY KEY REFERENCES users(id),
    balance INT NOT NULL DEFAULT 1000
);